// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BillingUsageUsage struct {
	EndTime      *string `json:"endTime,omitempty"`
	OwnerID      *string `json:"ownerId,omitempty"`
	ResourceID   *string `json:"resourceId,omitempty"`
	ResourceName *string `json:"resourceName,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
	StartTime    *string `json:"startTime,omitempty"`
	Value        *string `json:"value,omitempty"`
}

// BillingUsage - Represents a billing usage entity
type BillingUsage struct {
	// What the unit indicates
	Description *string `json:"description,omitempty"`
	// The metric name
	Metric *string             `json:"metric,omitempty"`
	Usage  []BillingUsageUsage `json:"usage,omitempty"`
}
