// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateWorkspaceGroup struct {
	AdminPassword    *string `json:"adminPassword,omitempty"`
	WorkspaceGroupID string  `json:"workspaceGroupID"`
}
