// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModifyStagesFile struct {
	// sample_file.txt
	Name *string `json:"name,omitempty"`
	// parent_folder/sample_file.txt
	Path *string `json:"path,omitempty"`
}
