// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PrivateConnectionOutboundAllowList - Represents information related to a private connection outbound allow list
type PrivateConnectionOutboundAllowList struct {
	// The account ID allowed for outbound connections
	OutboundAllowList *string `json:"outboundAllowList,omitempty"`
}
