// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RegionProvider - Name of the provider
type RegionProvider string

const (
	RegionProviderAws   RegionProvider = "AWS"
	RegionProviderGcp   RegionProvider = "GCP"
	RegionProviderAzure RegionProvider = "Azure"
)

func (e RegionProvider) ToPointer() *RegionProvider {
	return &e
}

func (e *RegionProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AWS":
		fallthrough
	case "GCP":
		fallthrough
	case "Azure":
		*e = RegionProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RegionProvider: %v", v)
	}
}

// Region - Represents information related to a region in which a workspace group is created
type Region struct {
	// Name of the provider
	Provider RegionProvider `json:"provider"`
	// Name of the region
	Region string `json:"region"`
	// ID of the region
	RegionID string `json:"regionID"`
}
