// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// StagesPatch - Represents information specified when modifying an object in Stages
type StagesPatch struct {
	// New path of the object
	NewPath *string `json:"newPath,omitempty"`
}
