// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateWindow - Represents information related to an update window
type UpdateWindow struct {
	// Day of week (0-6), starting on Sunday
	Day float64 `json:"day"`
	// Hour of day - 0 to 23 (UTC)
	Hour float64 `json:"hour"`
}
