// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceGroupUpdate - Represents the information specified while updating a workspace group
type WorkspaceGroupUpdate struct {
	// The admin password for the workspace group. The password must contain:
	//
	//   * At least 8 characters
	//   * At least one uppercase character
	//   * At least one lowercase character
	//   * At least one number or special character
	//
	AdminPassword *string `json:"adminPassword,omitempty"`
	// Whether to allow all traffic to the workspace group
	AllowAllTraffic *bool `json:"allowAllTraffic,omitempty"`
	// The timestamp of when the workspace group will expire. If the expiration time is not specified, the workspace group will have no expiration time. At expiration, the workspace group is terminated and all the data is lost. Expiration time can be specified as a timestamp or duration. For example,
	//
	//   * "2023-09-02T15:04:05Z07:00"
	//   * "2023-09-02T15:04:05-0700"
	//   * "2023-09-02T15:04:05"
	//   * "2023-09-02"
	//   * "3h30m"
	//
	ExpiresAt *string `json:"expiresAt,omitempty"`
	// A list of allowed CIDR ranges. An empty list indicates that no inbound requests are allowed.
	FirewallRanges []string `json:"firewallRanges,omitempty"`
	// Name of the workspace group
	Name *string `json:"name,omitempty"`
	// Represents information related to an update window
	UpdateWindow *UpdateWindow `json:"updateWindow,omitempty"`
}
