// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceCreate - Represents the information specified while creating a workspace
type WorkspaceCreate struct {
	// Whether to create a SingleStore Kai-enabled workspace
	EnableKai *bool `json:"enableKai,omitempty"`
	// Name of the workspace
	Name string `json:"name"`
	// Size of the workspace (in workspace size notation), such as "S-1". The default value is "S-00".
	//
	Size *string `json:"size,omitempty"`
	// ID of the workspace group in which the workspace is created
	WorkspaceGroupID string `json:"workspaceGroupID"`
}
