// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"singlestore/internal/sdk"
	"singlestore/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ provider.Provider = &SinglestoreProvider{}

type SinglestoreProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// SinglestoreProviderModel describes the provider data model.
type SinglestoreProviderModel struct {
	ServerURL  types.String `tfsdk:"server_url"`
	APIKeyAuth types.String `tfsdk:"api_key_auth"`
}

func (p *SinglestoreProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "singlestore"
	resp.Version = p.version
}

func (p *SinglestoreProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: `SingleStore Management API: The ` + "`" + `Management` + "`" + ` API can be used to create and manage workspaces, workspace groups, private connections, etc. SingleStore recommends reading the [` + "`" + `Management` + "`" + ` API Overview](https://docs.singlestore.com/managed-service/en/reference/management-api.html) before getting started with the API reference.` + "\n" +
			`` + "\n" +
			`All the URLs referenced in this API documentation use the ` + "`" + `https://api.singlestore.com` + "`" + ` service endpoint as their base.` + "\n" +
			``,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://api.singlestore.com)",
				Optional:            true,
				Required:            false,
			},
			"api_key_auth": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *SinglestoreProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data SinglestoreProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://api.singlestore.com"
	}

	apiKeyAuth := data.APIKeyAuth.ValueString()
	security := shared.Security{
		APIKeyAuth: apiKeyAuth,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *SinglestoreProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{}
}

func (p *SinglestoreProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &SinglestoreProvider{
			version: version,
		}
	}
}
