// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type BillingUsageUsage struct {
	EndTime      types.String `tfsdk:"end_time"`
	OwnerID      types.String `tfsdk:"owner_id"`
	ResourceID   types.String `tfsdk:"resource_id"`
	ResourceName types.String `tfsdk:"resource_name"`
	ResourceType types.String `tfsdk:"resource_type"`
	StartTime    types.String `tfsdk:"start_time"`
	Value        types.String `tfsdk:"value"`
}
