// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"singlestore/internal/sdk/pkg/models/shared"
)

type CreateWorkspaceGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateWorkspaceGroup *shared.CreateWorkspaceGroup
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
