// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"singlestore/internal/sdk/pkg/models/shared"
)

type DeleteWorkspaceGroupsRequest struct {
	// To terminate a workspace group even if it has active workspaces, set to `true`
	Force *bool `queryParam:"style=form,explode=true,name=force"`
	// ID of the workspace group
	WorkspaceGroupID string `pathParam:"style=simple,explode=false,name=workspaceGroupID"`
}

type DeleteWorkspaceGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TerminateWorkspaceGroups *shared.TerminateWorkspaceGroups
}
