// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"singlestore/internal/sdk/pkg/models/shared"
)

type UpdateStagesFileRequest struct {
	StagesPatch *shared.StagesPatch `request:"mediaType=application/json"`
	// Path in Stages to modify
	Path string `pathParam:"style=simple,explode=false,name=path"`
	// ID of the Stages-enabled workspace group
	WorkspaceGroupID string `pathParam:"style=simple,explode=false,name=workspaceGroupID"`
}

type UpdateStagesFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ModifyStagesFile *shared.ModifyStagesFile
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
