// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"singlestore/internal/sdk/pkg/models/shared"
)

type UpdatePrivateConnectionRequest struct {
	// Here's a sample of JSON data sent in the request body to the API.
	UpdatePrivateConnection shared.UpdatePrivateConnection `request:"mediaType=application/json"`
	// ID of the private connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connectionID"`
}

type UpdatePrivateConnectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UpdatePrivateConnectionResponse *shared.UpdatePrivateConnectionResponse
}
