// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"singlestore/internal/sdk/pkg/models/shared"
)

type UpdateWorkspaceGroupsRequest struct {
	// Here's a sample of JSON data sent to the API in the request body.
	WorkspaceGroupUpdate shared.WorkspaceGroupUpdate `request:"mediaType=application/json"`
	// ID of the workspace group
	WorkspaceGroupID string `pathParam:"style=simple,explode=false,name=workspaceGroupID"`
}

type UpdateWorkspaceGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UpdateWorkspaceGroups *shared.UpdateWorkspaceGroups
}
